name: PyTest
on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  # pull_request:

jobs:
  test-with-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install -r requirements-test.txt
          python -m playwright install --with-deps

      - name: Run tests
        run: python -m pytest
